keys:
  - &admin_gpg 873DF106014C63F7
  - &host_koch age12gr6jhhkgdjmgj7aj3kjgq6s439tsmgzg07muk7h2g525smc9c7q7k8dw8

creation_rules:
  - path_regex: nix/koch/secrets\.yaml$
    age:
      - *host_koch
    pgp:
      - *admin_gpg
