# Hardware configuration for sierpinski (HP Chromebook 14-db0003na, board careena)
#
# CPU:  AMD A4-9120C, Stoney Ridge, 2C/2T
# GPU:  Radeon R4, GCN 3 — amdgpu
# RAM:  4GB DDR4, soldered
# Disk: 32GB eMMC, soldered
# Boot: UEFI after the MrChromebox Full ROM conversion — systemd-boot
#
# Nothing is built on this machine. Closures are pushed from a fleet host.

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.loader.systemd-boot.enable = true;
  # Each retained generation pins a full closure — the biggest lever on 32GB
  boot.loader.systemd-boot.configurationLimit = 5;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.availableKernelModules = [
    "sdhci_pci"
    "mmc_block"
    "xhci_pci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Filesystem mounts are generated by disko from disk-config.nix
  swapDevices = [ ];

  # zram instead of a swap partition — swapping to eMMC is slow and wears it out
  zramSwap = {
    enable = true;
    memoryPercent = 50;
  };

  # Periodic trim rather than continuous discard
  services.fstrim.enable = true;

  hardware.graphics.enable = true;
  hardware.enableRedistributableFirmware = true;

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
