# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "nfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7a9afd6f-a60e-4b09-ba99-788664a2eb39";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F0F0-60C5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/tb" =
    { device = "/dev/disk/by-uuid/F8D8B7AAD8B76612";
      fsType = "ntfs3";
      options = ["nofail"];
    };

  fileSystems."/mnt/photos" =
    { device = "192.168.1.137:/mnt/Main Pool/Photos";
      fsType = "nfs";
      options = ["nofail" "x-systemd.automount" "noauto"];
    };

  fileSystems."/mnt/state-store" =
    { device = "192.168.1.137:/mnt/Main Pool/state-store";
      fsType = "nfs";
      options = ["nofail" "x-systemd.automount" "noauto"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6305ecf6-1c88-4b62-8667-82477ac4b7b0"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
