# Hardware configuration for koch (HP workstation NAS)
#
# CPU:  Intel Xeon E5-2667 v2 (8C/16T @ 3.3GHz)
# RAM:  64GB
# Boot: BIOS (not UEFI) — uses GRUB installed to both SSDs
# NIC:  Intel e1000e — needs EEE and interrupt throttle disabled
# HBA:  Broadcom/LSI SAS2008 (Dell 6Gbps) — mpt3sas driver
# SSDs: 250GB Crucial MX500 + 240GB Intel (btrfs RAID1, root)
# HDDs: 6x 4TB WD Red WD40EFRX (btrfs RAID1, data)

{ config, lib, pkgs, modulesPath, ... }: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # BIOS boot — disko handles GRUB device registration via the EF02 partitions
  # in disk-config.nix. No need to set boot.loader.grub.devices here.
  boot.loader.grub.enable = true;

  boot.initrd.availableKernelModules = [ "ahci" "mpt3sas" "sd_mod" "usb_storage" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # e1000e NIC: disable Energy Efficient Ethernet and interrupt throttling.
  # Without this the NIC drops packets under load on Proxmox/NixOS.
  boot.extraModprobeConfig = "options e1000e EEE=0 InterruptThrottleRate=0";

  # Filesystem mounts are generated by disko from disk-config.nix

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
